#!/bin/bash
if [ $# -lt 3 ]
then 
    echo "Usage: src2pdf <src-loc> <file-type1,file-type2,...> <out-file> [a2ps layout args (dont specify printer!)]"
    echo "Example: src2pdf ~/git/c-proj c,h ~/git/c-proj/doc -T4 --columns=1"
    echo "Default a2ps: a2ps --columns=2 -T3 -q"
    exit 0
fi

set -e

folder=`readlink -ve "$1"`
[[ $folder != */ ]] && folder+="/"

output=`readlink -vf "$3"`
[[ "$output" != *".pdf" ]] && output+=".pdf"

tmp="/tmp/src2pdf_$USER/"
[ -d "$tmp" ] || mkdir "$tmp"

lang="$2"
args="${*:4}"

echo "Search folder: $folder"
echo "File types: $lang"
echo "Output file: $output"
echo "Layout args: $args"

reg="'.*\\.\\(""$(echo "$lang" | sed 's.,.\\|.g')""\)'" 

eval "find $folder -regex $reg" | while read -r line
do
    a2ps --columns=2 -q -T3 $args -P pdf "$line"
    IFS='/' read -a patharray <<< "$line"
#    filename="${patharray[-1]%"."*}.pdf"
    mv "${patharray[-1]%"."*}.pdf" "$tmp"`echo "${line#$folder}" | tr "/" "."`".pdf"      
done

psfiles=$(echo `find "$tmp" -name "*.pdf"` | tr "\n" " ")
pdfunite $psfiles $output
rm -rf "$tmp"
echo "done"
